### ISSUE TITLE
Categories appear cut off

### ISSUE THREAD

**Issue by alba4k** [mijorus/smile#22]
FIrst of all, congratulations to @mijorus for this awesome program!

Now I'd like to point out a couple of issues I'm having with it.

The first and major one, which I'm opening the issue for, is that the emoji categories appear cut off by the edge of the window, no matter the size of it:
![immagine](https://user-images.githubusercontent.com/84153269/200011239-b78bcfec-b3e3-48c4-9585-f64e1906ab72.png)
![immagine](https://user-images.githubusercontent.com/84153269/200011427-a1af5254-8d9d-419c-9f28-5f4928610339.png)

Since it might be relevant, my current window manager is i3wm.

The second, smaller, thing is more of a feature request than a real issue: it would be quite nice if the program would use the system default emoji font (in my case, [Joypixels](https://joypixels.com/)) instead of noto (google) emojis.

Thanks a lot for the time spent creating this!

##### I also speak italian, answer however you're more comfortable doing

**Comment by mijorus** [comment]
Hi @alba4k ,

First of all, what kind of theme/distro are you using? (theme especially is relevant).
Are you using the package from the AUR?

**Comment by alba4k** [comment]
I am using the AUR package, with an old catppuccin gtk theme (you don't find it anymore, but you can find it in my [dotfiles](https://github.com/alba4k/.dotfiles/tree/master/.themes))

You are right, I don't have this issue when using GTK_THEME="Adwaita" or "Adwaita:dark"

Do you have any idea of what could be causing this?

**Comment by mijorus** [comment]
> I am using the AUR package, with an old catppuccin gtk theme (you don't find it anymore, but you can find it in my [dotfiles](https://github.com/alba4k/.dotfiles/tree/master/.themes))
> 
> You are right, I don't have this issue when using GTK_THEME="Adwaita" or "Adwaita:dark"
> 
> Do you have any idea of what could be causing this?

Yes, the AUR package.

And this is why this package is released only as a flatpak.

Because:
- Themes don't break
- All the emojis actually show up

You are lucky with the second one, as on some older distros some emojis are not showing up correctly unless we are inside the Flatpak environment.

To sum it up:
- Please, use the Flatpak version
- While your font looks pretty nice I have to say, I can't include it as it is a commercial product
- I have to provide my own font file, otherwise some emojis won't show up correctly.
- I could, however, let the user pick the font file they want to use from the filesystem, but that would be a feature request rather than a bug report

**Comment by mijorus** [comment]
I'm expanding the answer a little bit.

Unicodes are updated every once in a while.
In order to add features like skin tones , hairs , sex, flags and more, they have basically combined two emojis into one.

In this way, if you're trying to see this 👋🏿 on older software, it would still be rendered as 👋⬛.

So, what if the user is on Ubuntu 18.04? If I was using the system font, The emoji grid would look terrible because some cells would contain two characters

**Comment by alba4k** [comment]
I had already noticed that some emojis are indeed composite (ineed by the use of some programs with an own emoji rendering), and I can see how this could be an issue, yes. I'm a bit hesitant with flatpak, as it would be the only flatpak package I would have installed (and maybe steam, because often games want "ubuntu" versions of some libraries), but I will look into it.

I wish you a great continuation :)

**Comment by alba4k** [comment]
![immagine](https://user-images.githubusercontent.com/84153269/200068975-25714b0f-ef83-47e7-915a-1e36358b0726.png)
Well, things didn't go as expected. The exact same thing apparently happens with the flatpak aswell...

**Comment by mijorus** [comment]
Damn!😅

**Comment by alba4k** [comment]
So, I guess it's just that theme being broken ahah!

I guess that you don't really like its existance, but would you mind if I keep it, so I don't need flatpak installed for just one package? :P

**Comment by mijorus** [comment]
There is no need, thanks

**Comment by yochananmarqos** [comment]
> an old catppuccin gtk theme

Don't use an old, broken theme, maybe?

> I don't have this issue when using GTK_THEME="Adwaita" or "Adwaita:dark"

That's a debugging option and should not be used.

@mijorus I think this can be closed now.

**Comment by mijorus** [comment]
Libadwaita should now address this issue
