### ISSUE TITLE
Feature: bring to front if already running

### ISSUE THREAD

**Issue by sepehr** [mijorus/smile#23]
Not sure, how, but what could improve my experience is for the configured hotkey to bring the app to the front. First time I hit the hotkey, Smile appears, second time I get a notification `"smile" is ready" and I need to switch to it. 

I can imagine this can be done by using `wmctrl` on X11, but this is a Wayland case for which I'm not sure if there's a proper `wmctrl` alternative.

Would appreciate your input.

**Comment by mijorus** [comment]
Hi @sepehr , I am looking into this.

Can you please specify with OS you are running? thanks

**Comment by sepehr** [comment]
Hi @mijorus, thanks for that! I'm running Fedora 37, Gnome 43.2.

**Comment by mijorus** [comment]
Unfortunately, it seems that there is no way I can  address this issue 😢

**Comment by chiffshinz** [comment]
I solved it by using the [GNOME Extension](https://extensions.gnome.org/extension/6385/steal-my-focus-window/) [Steal my Focus](https://github.com/v-dimitrov/gnome-shell-extension-stealmyfocus). This will always put the focus on applications, which brings them to the front, instead of showing the notification.

Apparently this "App is ready"-Notification is an accessibility feature. I don't have the link to the official GNOME Docs, but i saw it in the top comment of [this StackExchange question](https://askubuntu.com/q/80969). (Comment is 6 years old, though)

@mijorus Maybe this info could be added to the README? Possibly this functionality could be added to the [Smile Complementary Extension](https://github.com/mijorus/smile-gnome-extension), as an option. By looking at the code of the Steal my Focus extension, I guess it should be quite easy to intercept the `window-demands-attention` event, then check the application id and if it's smile, focus on it, otherwise return, so the behaviour for other applications remains the same.
