### ISSUE TITLE
[Feature] Position window at mouse location

### ISSUE THREAD

**Issue by joenepraat** [mijorus/smile#34]
First thank you for this great application!

Would it be possible to position the window at the mouse location? Right now it's always positioned in the top left corner.

**Comment by mijorus** [comment]
Hi @joenepraat ,
I tried, but this feature is unreliable as it is up to the Window Manager to decide where windows will be place.
Furthermore, it's completely ignored on wayland.

Please do a quick online search on how to change the default position of new windows  for your distribution. If you are using GNOME, the best you can do is setting "center new windows" to TRUE with GNOME tweaks.


I'm sorry

**Comment by joenepraat** [comment]
Thanks for the tip @mijorus. That makes it a bit more bearable. 

I first used a similar app called [Emote](https://github.com/tom-james-watson/Emote), but for various reasons I now use your app. Emote positionions itself under the mouse cursor, but maybe that only works because I use X11 (under Ubuntu 22.04, Gnome 42) like you said.

**Comment by mijorus** [comment]
Emote is written with GTK3, which used to have this feature.

Smile 1.0 had this feature as well, but i decided to remove after the libadwaita rewrite, because it is unsupported by gtk4.

There are workarounds on x11, but I don't feel like it worth the effort.

If you really really really want, you can still use the last 1.x release
https://github.com/mijorus/smile/releases/tag/1.7.3

Please just make sure to uninstall the current version first.

**Comment by joenepraat** [comment]
Ok clear. No I prefer the 2.* release. So I will keep using your center tip.

Thanks for all the quick replies.

> Emote is written with GTK3, which used to have this feature.
> 
> Smile 1.0 had this feature as well, but i decided to remove after the libadwaita rewrite, because it is unsupported by gtk4.
> 
> There are workarounds on x11, but I don't feel like it worth the effort.
> 
> If you really really really want, you can still use the last 1.x release https://github.com/mijorus/smile/releases/tag/1.7.3
> 
> Please just make sure to uninstall the current version first.
