### ISSUE TITLE
Add an emoji without copying it to the clipboard?

### ISSUE THREAD

**Issue by callmehanu** [mijorus/smile#35]
Recently I switch to Linux, I until now I can't find a replacement for the Windows emoji picker.
**Smile** is great, but I wonder if is posible to add an emoji just pressing enter and avoid copping it to the clipboard and then paste in the input.

Also I've notice that sometimes when I trigger the Smile picker, it searchbar ins't focus... and that very frustrated.

Maybe I've can't configure correctly but anyway, send this message as feedback. 
Hope it could be usefull.!

**Comment by mijorus** [comment]
Hi @callmehanu,
Smile targets the latest version of Ubuntu/Fedora, which use Wayland by default.
If you don't know, Wayland is a new display protocol which, among other things, has some limitations in place.

> ut I wonder if is posible to add an emoji just pressing enter and avoid copping it to the

The answer is "not really". As far as I know, There are some workarounds on X11 (ubuntu 21.10 and older) but today there is no way for apps to interact with other windows, and this is by design of the OS.

Some emoji pickers, like Emote, take advantage of these old workarounds but they don't work anymore on the latest releases of Ubuntu/Fedora.

> Also I've notice that sometimes when I trigger the Smile picker, it searchbar ins't focus... and that very frustrated.

Again, there is nothing here (at least from the app), it's up to the OS to decide what is in focus and what not. You could try disabling "run in the background", which OS the app to create a new window every time you launch it.

**Comment by jasaldivara** [comment]
> Recently I switch to Linux, I until now I can't find a replacement for the Windows emoji picker. **Smile** is great, but I wonder if is posible to add an emoji just pressing enter and avoid copping it to the clipboard and then paste in the input.
> 

Gtk 3 and 4 apps already have an integrated emoji picker. You just have to press `Ctrl .` or `Ctrl ;` when inside a text entry. Not sure if that's what you are looking for.

**Comment by mijorus** [comment]
> Gtk 3 and 4 apps already have an integrated emoji picker. You just have to press `Ctrl .` or `Ctrl ;` when inside a text entry. Not sure if that's what you are looking for.

I'm sorry but that integration is almost useless, how is the user supposed to know then he is using a gtk app?
