### ISSUE TITLE
Add support for symbols, and Kaomojis

### ISSUE THREAD

**Issue by rohmishra** [mijorus/smile#40]
Add support for non emoji symbols, kaomojis and other content.

Example: https://support.microsoft.com/en-us/windows/windows-keyboard-tips-and-tricks-588e0b72-0fff-6d3f-aeee-6e5116097942

Adding support for clipboard would require a extension limited to gnome desktop but others should work anywhere.

**Comment by mijorus** [comment]
- Symbols and Kaomojis sound fine to me, but adding GIFs is a bad idea IMO, as I you would need to query external APIs that might break tomorrow. 

- If with 'extersion' you mean a system icon tray, I'm sorry but this is not planned as this feature as been removed from GTK (and it was made it clear they don't want new apps to use it)

**Comment by rohmishra** [comment]
> If with 'extersion' you mean a system icon tray, I'm sorry but this is not planned as this feature as been removed from GTK (and it was made it clear they don't want new apps to use it)

I had something else in mind but it would make it a gnome-dependent feature.

**Comment by ghassan0** [comment]
If you're interested in a similar app that also provides symbols, take a look at Gnome Characters and see if it fits your needs. I'm actually switching from it to Smile instead because of the symbols. I personally found that the addition of symbols felt like too much clutter when trying to search since 99% of the time I'm searching for an emoji.

**Comment by mijorus** [comment]
Sorry for the delay, I have an update on this one.

As of today, I'm not considering adding symbols and kaomojis to Smile, I'm sorry.
