### ISSUE TITLE
Add custom emojies to the list?

### ISSUE THREAD

**Issue by sepehr** [mijorus/smile#41]
I might be blind, but there's no :snake: there :sweat_smile: Is there any way to add custom emojies and bind them to custom tags? Would be helpful. 

Your work is much appreciated :blush:

**Comment by mijorus** [comment]
Hi @sepehr 
the emoji you mentioned is present, but it is tagged as "serpent"; sometimes tags are a bit messy, but that's why custom tags exist.

Personally, I have added these two custom tags:
<img width="400" alt="image" src="https://user-images.githubusercontent.com/39067225/231227266-39d3f2e5-715d-48a6-826e-a10279774679.png">

However, for exactly for reason, **you can paste an emoji in the searchbar** and it would search for it, just like it was a custom tag.

As for custom emojis, I'm sorry but I'm not interested in adding this feature.

**Comment by mijorus** [comment]
<img width="366" alt="image" src="https://user-images.githubusercontent.com/39067225/231228844-aff85f78-f707-4c8d-9236-23d87ecb634b.png">
