### ISSUE TITLE
UI hides in background after selecting Emoji

### ISSUE THREAD

**Issue by manikandancode** [mijorus/smile#5]
OS: Ubuntu 21.10 Wayland

https://user-images.githubusercontent.com/46480489/156768269-071676c4-3ed2-4263-8a5b-d98da7697215.mp4

**Comment by mijorus** [comment]
Hi, 
let me first say that I am quite inexperienced with GTK 😅, anyway...

This behavior is by design: by hiding the window I keep the process running in the background with means it will open faster the next time you launch the application.

The typical use-case I have in mind is that a user would assign Smile to a keyboard shortcut in the system settings and use that shortcut to open the app.

I have observed about 0.4/0.8 difference by using this trick, which btw has an impact on memory usage of around 70mb (there is probably some overhead caused by the flatpak), but I think is pretty manageable by a modern PC.

I think that Smile is the kind of tool for which the startup time is pretty important, so idk, maybe there drawbacks I am not aware of... let me know what you think.

**Comment by mijorus** [comment]
I also wanna mentioned that pressing the ESC key has the same effect: the window will be hidden but the process is still loaded in memory.

Clicking on the "✖️" button btw really closes the application and quits the process.

**Comment by manikandancode** [comment]
> behavior is by design

I think minimizing is better than hiding. It will also help to open the app easier for next emoji pick.

> use that shortcut to open the hidden app UI

Ok . But need to learn or set that shortcut first.

**Comment by mijorus** [comment]
> I think minimizing is better than hiding. It will also help to open the app easier for next emoji pick.

Personally, I don't think this would be a good user experience, because when you minimize the window your DE inevitably  shows an animation that would break typing flow, as the  sight would follow the window minimizing.
 
> > use that shortcut to open the hidden app UI
This is really a good point. 

1) I need to add a welcome window of some sort that informs the user about the feature. ✅
2) Creating a shortcut on most of the DEs is quite easy, I doubt that a linux user does not know how to create a custom shortcut. Personally, I don't really like apps intercepting shortcuts, which, can interfere with the system, but rater have a single centralized panel where I can set and customize all of them.
Apps like Diodon behave similarly, letting the user create his own shortcut as he wants.

Let me know what you think,
Thanks

**Comment by mijorus** [comment]
> > behavior is by design
> 
> I think minimizing is better than hiding. It will also help to open the app easier for next emoji pick.

I have updated the app with a toggle to choose weather to hide the window or minimizing it.

By default, the previous behaviour will be set but you can easily change it by going into the preferences.
