### ISSUE TITLE
Alternative download methods?

### ISSUE THREAD

**Issue by Sush-ruta** [mijorus/smile#6]
Hello.
Are you looking at alternative download methods like [snap](https://snapcraft.io/) or a .deb PPA?

P.S.: The app looks really nice. :) Thank you and good luck!

**Comment by mijorus** [comment]
Hi @Sush-ruta ,
About PPAs, no, this is not going to happen as I would have no time to maintain it.

.DEB could be, **BUT** I would have to do some testing as this app relies on Flatpak's Gnome 41 framework to display all the emojis correctly. This is because support for the latest emojis was only added recently, and so they would be displayed either incorrectly or with a combination of emojis, which would break the UI

SNAP: same story, testing is required, especially for performance. I want Smile to open quickly because it's a tool I need when typing a quick message or something. One for the reasons why I decided to create Smile is that I was unhappy with [Emote's](https://github.com/tom-james-watson/emote) performace, which is distributed with Snap
