### ISSUE TITLE
Smile is super slow on Ubuntu 24.04

### ISSUE THREAD

**Issue by danielbmeireles** [mijorus/smile#86]
## Basic data

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"

## Description

Every time I start Smiles, the app takes several minutes to open. I also checked that the background process is killed after I close the main app windows (the "run in background" permission is enabled for the app):

![image](https://github.com/user-attachments/assets/a1f43ac7-5757-4c3d-9410-ec2740e3a931)

The extension is installed, and I have the latest version:

![image](https://github.com/user-attachments/assets/3990b9e6-51b4-441f-a493-61004eef047b)

I can collect extended log information if required, I just need to have the instructions :)

**Comment by danielbmeireles** [comment]
Update: other emoji apps are also super slow on Ubuntu, like this one:

![image](https://github.com/user-attachments/assets/037a37fc-0521-48bc-b797-49dffe0e7b77)

I think the root cause is Ubuntu-related, but I could not confirm this.

**Comment by sents** [comment]
I am experiencing  a possibly related issue on NixOS (though other people on NixOS could not reproduce it).
All emoji pickers (including smile) relying on gtk are very slow. It seems that the emoji are hardware rendered. Once all emojis have been rendered the app is responsive but rendering takes a couple minutes. The issue seems to increase with the amount of emojis.

**Comment by danielbmeireles** [comment]
I removed the Noto Emoji font, and the side effects disappeared.
